name: Docker Build and Push

on:
  push:
    branches:
      - ss

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: "GitHub Action"
        run: pwd

      - name: 'Testing GitHub'
        run: echo ammar

      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ammarqassem --password dckr_pat_uXovz50EWYRhoDF3VfvgGqHPCno

    
